version: '3'
services:
  nodejs-server:
    build:
      context: ./api
    ports:
      - "3100:3100"
    container_name: node-api
    volumes:
       - ./api:/usr/src/app/api
       - /usr/src/app/api/node_modules
  react-ui:
    build:
      context: ./my_react_app
    ports:
      - "3000:3000"
    container_name: my_react_app
    stdin_open: true
    volumes:
       - ./my-app:/usr/src/app/my_react_app
       - /usr/src/app/my-app/node_modules